//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.22 at 09:09:43 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dpd.com/common/service/types/LoginService/2.0")
package com.dpd.common.ws.loginservice.v2_0.types;
