spring.devtools.restart.enabled=false
spring.devtools.restart.exclude.de_metas_util=/de.metas.util-[\\w.-]+\.jar
spring.devtools.restart.exclude.org_compiere_model=/org.compiere.model-[\\w.-]+\.jar
spring.devtools.restart.exclude.de_metas_adempiere=/de.metas.adempiere.[\\w.-]+\.jar