//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.18 at 10:36:55 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dpd.com/common/service/types/Authentication/2.0")
package com.dpd.common.ws.authentication.v2_0.types;
