#metasfresh.properties
#Fri Sep 12 21:01:16 ICT 2025
CDate=xyz2025-06-23 23\:23\:10.584
Warning=Do_not_change_any_of_the_data_as_they_will_have_undocumented_side_effects.
WarningD=Einstellungen_nicht_aendern,_da_diese_undokumentierte_Nebenwirkungen_haben.
UITheme=xyzmetas Fresh Theme
StorePassword=xyzY
AutoCommit=xyzY
spring.devtools.restart.enabled=false
ShowAcct=xyzY
Language=xyzEnglish
TraceFile=xyzN
ValidateConnectionOnStartup=xyzN
PrintPreview=xyzN
CacheWindow=xyzY
UILookFeel=xyzAdempiere
ShowTrl=xyzN
TempDir=xyz/tmp
AutoNew=xyzN
LoadTabMetaDataBackground=xyzN
SingleInstancePerWindow=xyzN
Connection=xyzCConnection[DBhost\=localhost,DBport\=5432,DBname\=metasfresh,UID\=metasfresh,PWD\=metasfresh]
Charset=xyzUTF-8
OpenWindowMaximized=xyzY
AutoLogin=xyzN
ShowAdvanced=xyzY
AdempiereSys=xyzN
TraceLevel=xyzWARNING
