//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.21 at 05:20:10 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dpd.com/common/service/types/ShipmentService/3.2")
package com.dpd.common.service.types.shipmentservice._3;
