//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.07.21 at 05:20:10 PM CEST 
//


package com.dpd.common.service.types.shipmentservice._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for startPosition.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="startPosition"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="UPPER_LEFT"/&gt;
 *     &lt;enumeration value="UPPER_RIGHT"/&gt;
 *     &lt;enumeration value="LOWER_LEFT"/&gt;
 *     &lt;enumeration value="LOWER_RIGHT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "startPosition")
@XmlEnum
public enum StartPosition {


    /**
     * Print first label in the upper left corner of the A4 paper.
     * 
     */
    UPPER_LEFT,

    /**
     * Print first label in the upper right corner of the A4 paper.
     * 
     */
    UPPER_RIGHT,

    /**
     * Print first label in the lower left corner of the A4 paper.
     * 
     */
    LOWER_LEFT,

    /**
     * Print first label in the lower right corner of the A4 paper.
     * 
     */
    LOWER_RIGHT;

    public String value() {
        return name();
    }

    public static StartPosition fromValue(String v) {
        return valueOf(v);
    }

}
